import GlobalButton from "@/components/GlobalButton";
import "./globals.css";
import AIChatPopup from "@/components/Aibot";

export const metadata = {
  title: "Travles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}
        <GlobalButton />
        <AIChatPopup />
      </body>
    </html>
  );
}
