// lib/packageData.js

export const packages = [
  {
    id: "char-dham-yatra",
    title: "Char Dham Yatra Complete Package",
    category: "spiritual",
    duration: "12 Days",
    price: "₹45,000",
    originalPrice: "₹55,000",
    rating: 4.8,
    reviews: 324,
    location: "Yamunotri, Gangotri, Kedarnath, Badrinath",
    groupSize: "6-8 people",
    image: "/package/chardham.webp",
    highlights: [
      "Four Sacred Shrines",
      "Spiritual Journey",
      "Professional Guide",
      "Helicopter Service Available",
      "Premium Accommodation",
    ],
    included: [
      "Comfortable Accommodation",
      "All Meals",
      "Transportation",
      "Experienced Guide",
      "Temple Entry Passes",
    ],
    description:
      "Embark on the most sacred pilgrimage in Hinduism covering Yamunotri, Gangotri, Kedarnath, and Badrinath. This spiritual journey takes you through ancient temples nestled in the majestic Himalayas.",
    bestTime: "May to October",
    itinerary: [
      "Day 1: Arrival in Haridwar, proceed to Barkot",
      "Day 2-3: Yamunotri Darshan and return to Uttarkashi",
      "Day 4-5: Gangotri Temple visit and overnight stay",
      "Day 6-8: Journey to Kedarnath via Guptkashi",
      "Day 9-11: Badrinath Darshan and local sightseeing",
      "Day 12: Return to Haridwar/Delhi departure",
    ],
    badge: "Most Popular",
    trending: true,
    views: "2.1k",
  },
  {
    id: "nainital-mussoorie-tour",
    title: "Nainital & Mussoorie Hill Station Tour",
    category: "family",
    duration: "6 Days",
    price: "₹18,000",
    originalPrice: "₹22,000",
    rating: 4.6,
    reviews: 156,
    location: "Nainital, Mussoorie, Dehradun",
    groupSize: "4-12 people",
    image: "/nainilake.jpeg",
    highlights: [
      "Naini Lake Boating",
      "Mall Road Shopping",
      "Kempty Falls",
      "Cable Car Rides",
      "Hill Station Views",
    ],
    included: [
      "Hotel Stay",
      "Breakfast & Dinner",
      "Sightseeing Tours",
      "Lake Activities",
      "Transportation",
    ],
    description:
      "Perfect family getaway to the beautiful hill stations with scenic views and pleasant weather. Experience the charm of colonial architecture, serene lakes, and misty mountains.",
    bestTime: "March to June, September to November",
    itinerary: [
      "Day 1: Arrival in Nainital, check-in and Naini Lake boating",
      "Day 2: Nainital local sightseeing - Snow View Point, Naina Devi Temple",
      "Day 3: Travel to Mussoorie, Mall Road evening walk",
      "Day 4: Mussoorie sightseeing - Kempty Falls, Gun Hill",
      "Day 5: Cable car ride, shopping and relaxation",
      "Day 6: Departure to Delhi/Dehradun",
    ],
    badge: "Family Favorite",
    views: "1.8k",
  },
  {
    id: "valley-of-flowers",
    title: "Valley of Flowers Trek",
    category: "adventure",
    duration: "8 Days",
    price: "₹25,000",
    originalPrice: "₹30,000",
    rating: 4.9,
    reviews: 89,
    location: "Chamoli, Valley of Flowers",
    groupSize: "6-10 people",
    image: "/trackingof vallyofflower.jpg",
    highlights: [
      "UNESCO World Heritage",
      "Rare Himalayan Flowers",
      "Professional Trek Guide",
      "Camping Experience",
      "Photography Paradise",
    ],
    included: [
      "Trekking Permits",
      "Guide & Porter",
      "Camping Equipment",
      "All Meals",
      "First Aid Kit",
    ],
    description:
      "Discover a UNESCO World Heritage site filled with endemic alpine flowers and rare wildlife. This high-altitude Himalayan valley is a paradise for nature lovers and trekkers.",
    bestTime: "July to September",
    itinerary: [
      "Day 1: Arrival in Haridwar, drive to Joshimath",
      "Day 2: Joshimath to Govindghat, trek to Ghangaria",
      "Day 3: Ghangaria to Valley of Flowers and back",
      "Day 4: Ghangaria to Hemkund Sahib and back",
      "Day 5-6: Trek back to Govindghat, drive to Rishikesh",
      "Day 7-8: Rishikesh sightseeing and departure",
    ],
    badge: "UNESCO Site",
    trending: true,
    views: "956",
  },
  {
    id: "jim-corbett-safari",
    title: "Jim Corbett Wildlife Safari",
    category: "wildlife",
    duration: "4 Days",
    price: "₹12,000",
    originalPrice: "₹15,000",
    rating: 4.7,
    reviews: 203,
    location: "Jim Corbett National Park",
    groupSize: "4-8 people",
    image: "/junglesafari1.jpg",
    highlights: [
      "Tiger Spotting",
      "Elephant Safari",
      "Bird Watching",
      "Nature Photography",
      "Wildlife Education",
    ],
    included: [
      "Safari Permits",
      "Accommodation",
      "All Meals",
      "Professional Guide",
      "Transportation",
    ],
    description:
      "Experience the wild side of Uttarakhand with exciting wildlife safaris in India's oldest national park. Home to the majestic Bengal tiger and diverse flora and fauna.",
    bestTime: "November to June",
    itinerary: [
      "Day 1: Arrival in Jim Corbett, check-in and evening safari",
      "Day 2: Early morning elephant safari, afternoon jeep safari",
      "Day 3: Full day wildlife activities and bird watching",
      "Day 4: Morning safari and departure",
    ],
    badge: "Wildlife Special",
    views: "1.2k",
  },
  {
    id: "rishikesh-adventure",
    title: "Rishikesh Adventure Package",
    category: "adventure",
    duration: "5 Days",
    price: "₹15,000",
    originalPrice: "₹18,000",
    rating: 4.5,
    reviews: 267,
    location: "Rishikesh, Haridwar",
    groupSize: "6-12 people",
    image: "/riverRafting.jpg",
    highlights: [
      "White Water Rafting",
      "Bungee Jumping",
      "Yoga Sessions",
      "Ganga Aarti",
      "Adventure Sports",
    ],
    included: [
      "Accommodation",
      "All Meals",
      "Adventure Activities",
      "Local Transportation",
      "Professional Instructor",
    ],
    description:
      "Ultimate adventure package combining thrilling activities with spiritual experiences in the yoga capital. Perfect blend of adrenaline rush and spiritual awakening.",
    bestTime: "October to June",
    itinerary: [
      "Day 1: Arrival in Rishikesh, evening Ganga Aarti",
      "Day 2: White water rafting and camping",
      "Day 3: Bungee jumping and adventure activities",
      "Day 4: Yoga session, local sightseeing",
      "Day 5: Final adventure activities and departure",
    ],
    badge: "Adventure Plus",
    views: "1.5k",
  },
  {
    id: "auli-ski-tour",
    title: "Auli Skiing & Joshimath Tour",
    category: "adventure",
    duration: "7 Days",
    price: "₹28,000",
    originalPrice: "₹35,000",
    rating: 4.8,
    reviews: 124,
    location: "Auli, Joshimath",
    groupSize: "4-10 people",
    image: "/package/View-of-snow-covered-mountains-from-Auli.jpg",
    highlights: [
      "World-Class Skiing",
      "Cable Car Rides",
      "Snow Activities",
      "Mountain Views",
      "Winter Sports",
    ],
    included: [
      "Ski Equipment",
      "Professional Instructor",
      "Accommodation",
      "All Meals",
      "Cable Car Tickets",
    ],
    description:
      "Winter sports paradise with world-class skiing facilities and breathtaking Himalayan views. Perfect destination for snow enthusiasts and adventure seekers.",
    bestTime: "December to March",
    itinerary: [
      "Day 1: Arrival in Joshimath, transfer to Auli",
      "Day 2-3: Skiing lessons and practice sessions",
      "Day 4-5: Advanced skiing and snow activities",
      "Day 6: Cable car ride and mountain exploration",
      "Day 7: Departure via Joshimath",
    ],
    badge: "Winter Special",
    trending: true,
    views: "867",
  },
];
